[package]
name = "weapon-designer"
version = "0.1.0"
authors = ["Matthew Dyer <rust@matthewdyer.io>"]
edition = "2018"

[dependencies]

rapier2d = { version = "0.9.2", features = [ "simd-stable" ] }
parry2d = "0.5.1"
piston_window = "0.120.0"
rand = "0.8"